# Generated by Django 5.1.4 on 2025-01-28 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoWebhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                ("url", models.URLField(verbose_name="URL")),
                ("ativa", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "usuario_atualizacao",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requests_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_criacao",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Webhook",
                "verbose_name_plural": "Configurações de Webhook",
            },
        ),
        migrations.CreateModel(
            name="ConfiguracaoSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ativa", models.BooleanField(default=True, verbose_name="Ativa")),
                ("create", models.BooleanField(default=True, verbose_name="Create")),
                ("update", models.BooleanField(default=True, verbose_name="Update")),
                ("delete", models.BooleanField(default=True, verbose_name="Delete")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "usuario_atualizacao",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requests_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_criacao",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "configuracao_webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="revalidacao_front.configuracaowebhook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Signal",
                "verbose_name_plural": "Configurações de Signal",
            },
        ),
    ]
