# Generated by Django 2.1.1 on 2020-08-12 20:00

import djrichtextfield.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templateemail",
            name="assunto",
            field=models.CharField(max_length=200, verbose_name="Assunto"),
        ),
        migrations.AlterField(
            model_name="templateemail",
            name="corpo_email",
            field=djrichtextfield.models.RichTextField(verbose_name="Corpo do email"),
        ),
    ]
