# Generated by Django 2.1.5 on 2020-12-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_auto_20200819_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateemail',
            name='destinatarios',
            field=models.ManyToManyField(blank=True, to='emails.Destinatario', verbose_name='Destinatários'),
        ),
    ]
