# Generated by Django 3.1.5 on 2021-03-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_auto_20201209_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateemail',
            name='legenda_email',
            field=models.CharField(default='', max_length=200, verbose_name='Legenda do email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='templateemail',
            name='titulo_alteracao_email',
            field=models.CharField(default='', max_length=200, verbose_name='Título alteração do email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='templateemail',
            name='titulo_email',
            field=models.CharField(default='', max_length=200, verbose_name='Título do email'),
            preserve_default=False,
        ),
    ]
