# Generated by Django 3.1.5 on 2021-03-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0006_auto_20210329_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateemail',
            name='foto_corpo',
            field=models.ImageField(blank=True, null=True, upload_to='template_emails/', verbose_name='Foto do corpo do email'),
        ),
        migrations.AddField(
            model_name='templateemail',
            name='imagem_capa',
            field=models.ImageField(blank=True, null=True, upload_to='template_emails/', verbose_name='Imagem de Capa'),
        ),
    ]
