# Generated by Django 3.1.5 on 2021-03-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0007_auto_20210330_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateemail',
            name='foto_corpo',
            field=models.ImageField(null=True, upload_to='template_emails/', verbose_name='Foto do corpo do email'),
        ),
        migrations.AlterField(
            model_name='templateemail',
            name='imagem_capa',
            field=models.ImageField(null=True, upload_to='template_emails/', verbose_name='Imagem de Capa'),
        ),
    ]
