# Generated by Django 3.2.4 on 2021-09-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0009_auto_20210806_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateemail',
            name='legenda_email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Legenda do email'),
        ),
        migrations.AlterField(
            model_name='templateemail',
            name='titulo_alteracao_email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título alteração do email'),
        ),
    ]
