# Generated by Django 3.2.8 on 2021-10-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0010_auto_20210903_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateemail',
            name='foto_corpo',
            field=models.ImageField(blank=True, null=True, upload_to='template_emails/', verbose_name='Foto do corpo do email'),
        ),
        migrations.AlterField(
            model_name='templateemail',
            name='imagem_capa',
            field=models.ImageField(blank=True, null=True, upload_to='template_emails/', verbose_name='Imagem de Capa'),
        ),
    ]
