# Generated by Django 3.2.8 on 2021-10-21 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0011_auto_20211020_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateemail',
            name='foto_corpo',
        ),
        migrations.RemoveField(
            model_name='templateemail',
            name='imagem_capa',
        ),
    ]
