# Generated by Django 3.0 on 2022-01-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0012_auto_20211021_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinatario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mensagememail',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='templateemail',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
