# Generated by Django 3.2.7 on 2022-02-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0013_auto_20220104_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinatario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mensagememail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='templateemail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
