# Generated by Django 3.0 on 2022-03-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0014_auto_20220215_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinatario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mensagememail',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='templateemail',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
