# Generated by Django 3.2.8 on 2022-03-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0016_auto_20220307_0930'),
        ('emails', '0016_auto_20220307_1015'),
    ]

    operations = [
    ]
