# Generated by Django 5.0.6 on 2024-12-17 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0017_merge_0016_auto_20220307_0930_0016_auto_20220307_1015"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="mensagememail",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_requests_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
