# Generated by Django 4.2.16 on 2025-08-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0019_configuracaoemail"),
    ]

    operations = [
        migrations.AddField(
            model_name="mensagememail",
            name="assunto",
            field=models.CharField(max_length=200, null=True, verbose_name="Assunto"),
        ),
    ]
