# Generated by Django 4.2.16 on 2025-08-18 13:15

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0020_mensagememail_assunto"),
    ]

    operations = [
        migrations.AddField(
            model_name="mensagememail",
            name="codigo",
            field=models.CharField(max_length=50, null=True, verbose_name="Código"),
        ),
        migrations.AddField(
            model_name="mensagememail",
            name="corpo_email",
            field=django_quill.fields.QuillField(
                null=True, verbose_name="Corpo do email"
            ),
        ),
        migrations.AddField(
            model_name="mensagememail",
            name="corpo_email_text",
            field=models.TextField(null=True, verbose_name="Corpo do email em texto"),
        ),
        migrations.AddField(
            model_name="mensagememail",
            name="destinatarios",
            field=models.ManyToManyField(
                blank=True, to="emails.destinatario", verbose_name="Destinatários"
            ),
        ),
        migrations.AddField(
            model_name="mensagememail",
            name="enviar_usuario_criacao",
            field=models.BooleanField(
                default=False, verbose_name="Enviar usuário de criação"
            ),
        ),
        migrations.AddField(
            model_name="mensagememail",
            name="legenda_email",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Legenda do email"
            ),
        ),
        migrations.AddField(
            model_name="mensagememail",
            name="titulo_alteracao_email",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Título alteração do email",
            ),
        ),
        migrations.AddField(
            model_name="mensagememail",
            name="titulo_email",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Título do email"
            ),
        ),
    ]
