# Generated by Django 4.2.16 on 2025-08-18 13:16

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0021_mensagememail_codigo_mensagememail_corpo_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templateemail",
            name="corpo_email",
            field=django_quill.fields.QuillField(verbose_name="Corpo do email"),
        ),
    ]
