# Generated by Django 4.2.16 on 2025-08-20 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("emails", "0022_alter_templateemail_corpo_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnexoEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de atualização"
                    ),
                ),
                (
                    "nome_interno",
                    models.CharField(
                        help_text="Nome interno do anexo, utilizado para identificar o anexo no sistema.",
                        max_length=200,
                        verbose_name="Nome interno do anexo",
                    ),
                ),
                (
                    "anexo",
                    models.FileField(upload_to="emails/anexos/", verbose_name="Anexo"),
                ),
                (
                    "template_email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="emails.templateemail",
                        verbose_name="Template de e-mail",
                    ),
                ),
                (
                    "usuario_atualizacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requests_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário de atualização",
                    ),
                ),
                (
                    "usuario_criacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requests_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário de criação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anexo de e-mail",
                "verbose_name_plural": "Anexos de e-mail",
            },
        ),
    ]
