# Generated by Django 4.2.16 on 2025-08-28 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("emails", "0023_anexoemail"),
    ]

    operations = [
        migrations.AddField(
            model_name="templateemail",
            name="ativo",
            field=models.BooleanField(default=True, verbose_name="Ativo"),
        ),
        migrations.AddField(
            model_name="templateemail",
            name="data_atualizacao",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data de atualização"
            ),
        ),
        migrations.AddField(
            model_name="templateemail",
            name="data_criacao",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Data de criação",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="templateemail",
            name="enviar_copia_oculta",
            field=models.ManyToManyField(
                blank=True,
                related_name="destinatarios_copia_oculta",
                to="emails.destinatario",
                verbose_name="Enviar cópia oculta",
            ),
        ),
        migrations.AddField(
            model_name="templateemail",
            name="logo_superior",
            field=models.FileField(
                null=True, upload_to="emails/logos/", verbose_name="Logo superior"
            ),
        ),
        migrations.AddField(
            model_name="templateemail",
            name="nome_interno",
            field=models.CharField(
                help_text="Nome interno do template, utilizado para identificar o template no sistema.",
                max_length=200,
                null=True,
                verbose_name="Nome interno do template",
            ),
        ),
        migrations.AddField(
            model_name="templateemail",
            name="primeiro_link",
            field=models.URLField(blank=True, null=True, verbose_name="Primeiro link"),
        ),
        migrations.AddField(
            model_name="templateemail",
            name="responder_para",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Responder para"
            ),
        ),
        migrations.AddField(
            model_name="templateemail",
            name="segundo_link",
            field=models.URLField(blank=True, null=True, verbose_name="Segundo link"),
        ),
        migrations.AddField(
            model_name="templateemail",
            name="smtp_especifico",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="emails.configuracaoemail",
                verbose_name="SMTP específico",
            ),
        ),
        migrations.AddField(
            model_name="templateemail",
            name="texto_acima_titulo",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Texto acima do título",
            ),
        ),
        migrations.AddField(
            model_name="templateemail",
            name="texto_primeiro_link",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Texto do primeiro link",
            ),
        ),
        migrations.AddField(
            model_name="templateemail",
            name="texto_segundo_link",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Texto do segundo link",
            ),
        ),
        migrations.AddField(
            model_name="templateemail",
            name="tipo_objeto",
            field=models.ForeignKey(
                blank=True,
                help_text="Tipo de objeto relacionado ao template de email",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
                verbose_name="Tipo de objeto",
            ),
        ),
        migrations.AddField(
            model_name="templateemail",
            name="usuario_atualizacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_requests_modified",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário de atualização",
            ),
        ),
        migrations.AddField(
            model_name="templateemail",
            name="usuario_criacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_requests_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário de criação",
            ),
        ),
        migrations.AlterField(
            model_name="templateemail",
            name="corpo_email",
            field=tinymce.models.HTMLField(verbose_name="Corpo do email"),
        ),
    ]
