# Generated by Django 4.2.16 on 2025-08-28 14:56

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0024_templateemail_ativo_templateemail_data_atualizacao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mensagememail",
            name="destinatario_extra",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Destinatário extra"
            ),
        ),
        migrations.AlterField(
            model_name="mensagememail",
            name="corpo_email",
            field=tinymce.models.HTMLField(null=True, verbose_name="Corpo do email"),
        ),
    ]
