# Generated by Django 5.0.6 on 2024-12-17 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Beneficio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "usuario_atualizacao",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requests_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_criacao",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Benefício",
                "verbose_name_plural": "Benefícios",
            },
        ),
        migrations.CreateModel(
            name="Candidato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                ("sobre_mim", models.TextField(verbose_name="Sobre Mim")),
                ("email", models.EmailField(max_length=100, verbose_name="E-mail")),
                ("whatsapp", models.CharField(max_length=20, verbose_name="WhatsApp")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapá"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PA", "Pará"),
                            ("PB", "Paraíba"),
                            ("PR", "Paraná"),
                            ("PE", "Pernambuco"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SP", "São Paulo"),
                            ("SE", "Sergipe"),
                            ("TO", "Tocantins"),
                        ],
                        max_length=2,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "expectativa_2anos",
                    models.TextField(
                        verbose_name="Expectativa para os próximos 2 anos"
                    ),
                ),
                (
                    "expectativa_10anos",
                    models.TextField(
                        verbose_name="Expectativa para os próximos 10 anos"
                    ),
                ),
                (
                    "comunicativo",
                    models.BooleanField(default=False, verbose_name="Comunicativo"),
                ),
                (
                    "ingles",
                    models.IntegerField(
                        choices=[
                            (0, "Não tem"),
                            (1, "Básico"),
                            (2, "Intermediário"),
                            (3, "Avançado"),
                            (4, "Fluente"),
                        ],
                        default=0,
                        verbose_name="Inglês",
                    ),
                ),
                (
                    "empregado",
                    models.BooleanField(default=False, verbose_name="Empregado"),
                ),
                (
                    "disponibilidade",
                    models.CharField(
                        choices=[
                            ("IMEDIATA", "Imediata"),
                            ("30DIAS", "30 dias"),
                            ("60DIAS", "60 dias"),
                            ("90DIAS", "90 dias"),
                            ("120DIAS", "120 dias"),
                        ],
                        default="IMEDIATA",
                        max_length=8,
                        verbose_name="Disponibilidade",
                    ),
                ),
                (
                    "horarios",
                    models.CharField(
                        choices=[
                            ("PART-TIME", "Part-time"),
                            ("FULL-TIME", "Full-time"),
                        ],
                        default="FULL-TIME",
                        max_length=9,
                        verbose_name="Horários",
                    ),
                ),
                (
                    "pretensao_salarial_pj",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Pretensão Salarial PJ",
                    ),
                ),
                (
                    "pretensao_salarial_clt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Pretensão Salarial CLT",
                    ),
                ),
                (
                    "curriculum",
                    models.FileField(upload_to="curriculos", verbose_name="Currículo"),
                ),
                (
                    "github_portfolio",
                    models.URLField(
                        blank=True, null=True, verbose_name="GitHub/Porfolio"
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "usuario_atualizacao",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requests_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_criacao",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidato",
                "verbose_name_plural": "Candidatos",
            },
        ),
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "usuario_atualizacao",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requests_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_criacao",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Curso",
                "verbose_name_plural": "Cursos",
            },
        ),
        migrations.CreateModel(
            name="Instituicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "usuario_atualizacao",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requests_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_criacao",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Instituição",
                "verbose_name_plural": "Instituições",
            },
        ),
        migrations.CreateModel(
            name="FormacaoCandidato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grau",
                    models.DecimalField(
                        choices=[
                            (0.5, "Técnico Incompleto"),
                            (1.0, "Técnico"),
                            (1.5, "Graduação Incompleta"),
                            (2.0, "Graduação"),
                            (2.5, "Pós-Graduação Incompleta"),
                            (3.0, "Pós-Graduação"),
                            (3.5, "Mestrado Incompleto"),
                            (4.0, "Mestrado"),
                            (4.5, "Doutorado Incompleto"),
                            (5.0, "Doutorado"),
                        ],
                        decimal_places=1,
                        default=2.0,
                        max_digits=2,
                        verbose_name="Grau",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Data de Início")),
                (
                    "data_conclusao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Conclusão"
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "candidato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recrutamento.candidato",
                        verbose_name="Candidato",
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recrutamento.curso",
                        verbose_name="Curso",
                    ),
                ),
                (
                    "usuario_atualizacao",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requests_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_criacao",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instituicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recrutamento.instituicao",
                        verbose_name="Instituição",
                    ),
                ),
            ],
            options={
                "verbose_name": "Benefício",
                "verbose_name_plural": "Benefícios",
            },
        ),
        migrations.CreateModel(
            name="PerguntaAberta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100, verbose_name="Título")),
                (
                    "obrigatorio",
                    models.BooleanField(default=True, verbose_name="Obrigatório"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "usuario_atualizacao",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requests_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_criacao",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pergunta Aberta",
                "verbose_name_plural": "Perguntas Abertas",
            },
        ),
        migrations.CreateModel(
            name="RespostaAberta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resposta",
                    models.TextField(blank=True, null=True, verbose_name="Resposta"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "candidato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recrutamento.candidato",
                        verbose_name="Candidato",
                    ),
                ),
                (
                    "pergunta_aberta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recrutamento.perguntaaberta",
                        verbose_name="Pergunta",
                    ),
                ),
                (
                    "usuario_atualizacao",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requests_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_criacao",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Resposta Aberta",
                "verbose_name_plural": "Respostas Abertas",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "tipo",
                    models.CharField(
                        choices=[("HARD", "Hard Skill"), ("SOFT", "Soft Skill")],
                        default="HARD",
                        max_length=4,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "usuario_atualizacao",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requests_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_criacao",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
            },
        ),
        migrations.CreateModel(
            name="SkillCandidato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avaliacao",
                    models.IntegerField(
                        choices=[
                            (0, "Não Possui"),
                            (1, "Básico"),
                            (2, "Intermediário"),
                            (3, "Avançado"),
                            (4, "Especialista"),
                        ],
                        default=0,
                        verbose_name="Avaliação",
                    ),
                ),
                (
                    "tempo_experiencia",
                    models.IntegerField(
                        choices=[
                            (0, "Não Possui"),
                            (1, "Menos de 1 ano"),
                            (2, "1 a 3 anos"),
                            (3, "3 a 5 anos"),
                            (4, "Mais de 5 anos"),
                        ],
                        default=0,
                        verbose_name="Tempo de Experiência",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "candidato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recrutamento.candidato",
                        verbose_name="Candidato",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recrutamento.skill",
                        verbose_name="Skill",
                    ),
                ),
                (
                    "usuario_atualizacao",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requests_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_criacao",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Skill do Candidato",
                "verbose_name_plural": "Skills dos Candidatos",
            },
        ),
        migrations.CreateModel(
            name="Vaga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100, verbose_name="Título")),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "tipo_contratacao",
                    models.CharField(
                        choices=[
                            ("CLT", "CLT"),
                            ("PJ", "PJ"),
                            ("ESTAGIO", "Estágio"),
                            ("FREELANCER", "Freelancer"),
                        ],
                        default="CLT",
                        max_length=10,
                        verbose_name="Tipo de Contratação",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "beneficios",
                    models.ManyToManyField(
                        blank=True,
                        to="recrutamento.beneficio",
                        verbose_name="Benefícios",
                    ),
                ),
                (
                    "diferenciais",
                    models.ManyToManyField(
                        blank=True,
                        related_name="vaga_diferenciais",
                        to="recrutamento.skill",
                        verbose_name="Diferenciais",
                    ),
                ),
                (
                    "requisitos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="vaga_requisitos",
                        to="recrutamento.skill",
                        verbose_name="Requisitos",
                    ),
                ),
                (
                    "usuario_atualizacao",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requests_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_criacao",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vaga",
                "verbose_name_plural": "Vagas",
            },
        ),
        migrations.AddField(
            model_name="perguntaaberta",
            name="vaga",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recrutamento.vaga",
                verbose_name="Vaga",
            ),
        ),
    ]
