# Generated by Django 5.0.6 on 2024-12-17 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recrutamento", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidato",
            old_name="curriculum",
            new_name="curriculo",
        ),
    ]
