# Generated by Django 3.2.12 on 2024-12-23 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recrutamento", "0002_rename_curriculum_candidato_curriculo"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaga",
            name="data_fechamento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Fechamento"
            ),
        ),
        migrations.CreateModel(
            name="AreaAtuacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "usuario_atualizacao",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="areaatuacao_requests_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_criacao",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="areaatuacao_requests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Área de Atuação",
                "verbose_name_plural": "Áreas de Atuações",
            },
        ),
    ]
