# Generated by Django 3.2.12 on 2024-12-23 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recrutamento", "0003_auto_20241223_1333"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaga",
            name="area_atuacao",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="recrutamento.areaatuacao",
                verbose_name="Área de Atuação",
            ),
        ),
        migrations.AddField(
            model_name="vaga",
            name="salario",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Salário"
            ),
        ),
        migrations.AddField(
            model_name="vaga",
            name="tipo_regime_trabalho",
            field=models.CharField(
                choices=[
                    ("PRESENCIAL", "Presencial"),
                    ("HIBRIDO", "Híbrido"),
                    ("HOME_OFFICE", "Home Office"),
                ],
                default="PRESENCIAL",
                max_length=20,
                verbose_name="Tipo de Regime de Trabalho",
            ),
        ),
    ]
