# Generated by Django 3.2.12 on 2024-12-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutamento', '0004_auto_20241223_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='responsabilidades',
            field=models.TextField(blank=True, null=True, verbose_name='Responsabilidades'),
        ),
    ]
