# Generated by Django 5.1.4 on 2024-12-27 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutamento', '0005_vaga_responsabilidades'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='descricao',
        ),
        migrations.AddField(
            model_name='candidato',
            name='data_nascimento',
            field=models.DateField(null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='Linkedin'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='sobre',
            field=models.TextField(blank=True, null=True, verbose_name='Sobre a Vaga'),
        ),
        migrations.AlterField(
            model_name='areaatuacao',
            name='usuario_atualizacao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_requests_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='areaatuacao',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='skillcandidato',
            name='tempo_experiencia',
            field=models.IntegerField(choices=[(0, 'Não Possui'), (1, 'Mais de 1 ano'), (2, 'Mais de 2 anos'), (3, 'Mais de 3 anos'), (4, 'Mais de 4 anos'), (5, 'Mais de 5 anos'), (6, 'Mais de 6 anos'), (7, 'Mais de 7 anos'), (8, 'Mais de 8 anos'), (9, 'Mais de 9 anos'), (10, 'Mais de 10 anos')], default=0, verbose_name='Tempo de Experiência'),
        ),
    ]
