# Generated by Django 5.1.4 on 2024-12-27 12:14

import django_editorjs.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recrutamento', '0006_remove_vaga_descricao_candidato_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='responsabilidades',
            field=django_editorjs.fields.EditorJsField(blank=True, null=True, verbose_name='Responsabilidades'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='sobre',
            field=django_editorjs.fields.EditorJsField(blank=True, null=True, verbose_name='Sobre a Vaga'),
        ),
    ]
