# Generated by Django 5.1.4 on 2024-12-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutamento', '0007_alter_vaga_responsabilidades_alter_vaga_sobre'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
