# Generated by Django 5.1.4 on 2025-01-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recrutamento", "0008_vaga_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formacaocandidato",
            name="grau",
            field=models.IntegerField(
                choices=[
                    (1, "Técnico Incompleto"),
                    (2, "Técnico"),
                    (3, "Graduação Incompleta"),
                    (4, "Graduação"),
                    (5, "Pós-Graduação Incompleta"),
                    (6, "Pós-Graduação"),
                    (7, "Mestrado Incompleto"),
                    (8, "Mestrado"),
                    (9, "Doutorado Incompleto"),
                    (10, "Doutorado"),
                ],
                default=1,
                verbose_name="Grau",
            ),
        ),
    ]
