# Generated by Django 5.1.4 on 2025-01-15 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recrutamento", "0009_alter_formacaocandidato_grau"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidato",
            name="vaga",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="recrutamento.vaga",
                verbose_name="Vaga",
            ),
        ),
    ]
