# Generated by Django 5.1.4 on 2025-01-16 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recrutamento", "0010_candidato_vaga"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vaga",
            options={},
        ),
    ]
