# Generated by Django 5.1.4 on 2025-01-16 09:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recrutamento", "0011_alter_vaga_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vaga",
            options={"verbose_name": "Vaga", "verbose_name_plural": "Vagas"},
        ),
    ]
