# Generated by Django 5.1.4 on 2025-01-28 13:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recrutamento", "0012_alter_vaga_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="areaatuacao",
            options={
                "ordering": ["nome"],
                "verbose_name": "Área de Atuação",
                "verbose_name_plural": "Áreas de Atuações",
            },
        ),
        migrations.AlterModelOptions(
            name="beneficio",
            options={
                "ordering": ["nome"],
                "verbose_name": "Benefício",
                "verbose_name_plural": "Benefícios",
            },
        ),
        migrations.AlterModelOptions(
            name="curso",
            options={
                "ordering": ["nome"],
                "verbose_name": "Curso",
                "verbose_name_plural": "Cursos",
            },
        ),
        migrations.AlterModelOptions(
            name="instituicao",
            options={
                "ordering": ["nome"],
                "verbose_name": "Instituição",
                "verbose_name_plural": "Instituições",
            },
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={
                "ordering": ["nome"],
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
            },
        ),
    ]
