# Generated by Django 4.2.16 on 2025-07-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recrutamento",
            "0013_alter_areaatuacao_options_alter_beneficio_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="candidato",
            name="indicacao",
            field=models.TextField(blank=True, null=True, verbose_name="Indicação"),
        ),
    ]
