# Generated by Django 4.2.16 on 2025-07-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recrutamento", "0014_candidato_indicacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaga",
            name="teste_tecnico",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="testes_tecnicos/",
                verbose_name="Teste Técnico",
            ),
        ),
    ]
