# Generated by Django 4.2.16 on 2025-07-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recrutamento", "0015_vaga_teste_tecnico"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidato",
            name="link_teste_tecnico",
            field=models.URLField(
                blank=True, null=True, verbose_name="Link do Teste Técnico"
            ),
        ),
        migrations.AddField(
            model_name="candidato",
            name="teste_tecnico",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="testes_tecnicos/",
                verbose_name="Teste Técnico",
            ),
        ),
    ]
