# Generated by Django 4.2.16 on 2025-07-31 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recrutamento", "0016_candidato_link_teste_tecnico_candidato_teste_tecnico"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="candidato",
            constraint=models.UniqueConstraint(
                fields=("email", "vaga"), name="unique_email_vaga"
            ),
        ),
    ]
