# Generated by Django 4.2.16 on 2025-08-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recrutamento", "0017_candidato_unique_email_vaga"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidato",
            name="cpf",
            field=models.CharField(
                blank=True,
                help_text="Apenas números, sem pontos ou traços.",
                max_length=11,
                null=True,
                verbose_name="CPF",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidato",
            constraint=models.UniqueConstraint(
                fields=("cpf", "vaga"), name="unique_cpf_vaga"
            ),
        ),
    ]
