# Generated by Django 4.2.16 on 2025-09-04 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recrutamento", "0018_candidato_cpf_candidato_unique_cpf_vaga"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="candidato",
            name="unique_cpf_vaga",
        ),
    ]
