# Generated by Django 4.2.16 on 2025-09-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recrutamento", "0019_remove_candidato_unique_cpf_vaga"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidato",
            name="resposta_vaga_generica",
            field=models.TextField(
                blank=True,
                help_text="Ex: Analista de Dados Pleno",
                null=True,
                verbose_name="Para qual cargo e nível você gostaria de se candidatar?",
            ),
        ),
        migrations.AddField(
            model_name="vaga",
            name="vaga_generica",
            field=models.BooleanField(
                default=False,
                help_text="Marque se esta vaga for genérica",
                verbose_name="Vaga genérica",
            ),
        ),
    ]
