# Generated by Django 4.2.16 on 2025-10-08 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recrutamento", "0020_candidato_resposta_vaga_generica_vaga_vaga_generica"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillsResposta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resposta",
                    models.TextField(blank=True, null=True, verbose_name="Resposta"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "candidato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recrutamento.candidato",
                        verbose_name="Candidato",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recrutamento.skill",
                        verbose_name="Skill",
                    ),
                ),
                (
                    "usuario_atualizacao",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requests_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_criacao",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Skills Resposta",
                "verbose_name_plural": "Skills Resposta",
            },
        ),
    ]
