# Generated by Django 4.2.16 on 2025-10-08 14:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recrutamento", "0021_skillsresposta"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SkillsResposta",
            new_name="SkillResposta",
        ),
    ]
