# Generated by Django 4.2.16 on 2025-10-08 19:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recrutamento", "0022_rename_skillsresposta_skillresposta"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SkillResposta",
            new_name="RepostaCandidatoSkillDiferencial",
        ),
        migrations.AlterModelOptions(
            name="repostacandidatoskilldiferencial",
            options={
                "verbose_name": "Resposta Candidato Skill Diferencial",
                "verbose_name_plural": "Respostas Candidato Skill Diferencial",
            },
        ),
    ]
