# Generated by Django 4.2.16 on 2025-10-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recrutamento",
            "0023_rename_skillresposta_repostacandidatoskilldiferencial_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="repostacandidatoskilldiferencial",
            name="resposta",
            field=models.BooleanField(blank=True, null=True, verbose_name="Resposta"),
        ),
    ]
