# Generated by Django 4.2.16 on 2025-10-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recrutamento", "0024_alter_repostacandidatoskilldiferencial_resposta"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidato",
            name="interesse_diferenciais",
            field=models.TextField(
                blank=True,
                help_text="Explique brevemente seu interesse ou contato com os diferenciais escolhidos.",
                null=True,
                verbose_name="Interesse ou contato com os diferenciais",
            ),
        ),
    ]
