# Generated by Django 4.2.16 on 2025-12-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recrutamento", "0025_candidato_interesse_diferenciais"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="peso",
            field=models.IntegerField(
                choices=[
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                ],
                default=1,
                verbose_name="Peso",
            ),
        ),
    ]
