# Generated by Django 4.2.16 on 2025-12-01 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recrutamento", "0027_pesoskill"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="peso",
        ),
    ]
